### ISSUE TITLE
July 27 fix details needed

### ISSUE THREAD

**Issue by dmiyamasu** [crdschurch/worship-training#4]
@samueljmello and @lukemoderwell 
Any info to share on how you resolved the issue today?

**Comment by samueljmello** [comment]
Yes. The problem was two fold:

1.) The column name for the trainees name had changed (a space was added) and the app couldn't find the specified column any more (looking for `.TraineeName` instead of `.["Trainee Name"]` on the object).

2.) The requests to AirTable to get the selected trainee data were taking too long (Heroku was timing out) and Slack expects a response in no more than 3 seconds. I updated the request to AirTable to do the filtering (and sorting) and used the `firstPage` method instead of `eachPage` that the AirTable JS library provides. We had previously been getting all data back (which I think was too large for Heroku's limits) and it was timing out as a result. I'm not 100% certain as to what those limits are with Heroku or why it mattered, but it just did.

I also updated documentation to reflect environment set-up and trouble shooting.
